return {
  -- Add the community repository of plugin specifications
  "AstroNvim/astrocommunity",
  { import = "astrocommunity.colorscheme.kanagawa-nvim" },
  { import = "astrocommunity.bars-and-lines.lualine-nvim"},
  { import = "astrocommunity.editing-support.dial-nvim"},
  { import = "astrocommunity.editing-support.cloak-nvim"},
  { import = "astrocommunity.editing-support.comment-box-nvim"},
  { import = "astrocommunity.editing-support.text-case-nvim"},
  { import = "astrocommunity.editing-support.true-zen-nvim"},
  { import = "astrocommunity.editing-support.todo-comments-nvim"},
  { import = "astrocommunity.editing-support.telescope-undo-nvim"},
  { import = "astrocommunity.editing-support.suda-vim"},
  { import = "astrocommunity.editing-support.refactoring-nvim"},
  { import = "astrocommunity.editing-support.rainbow-delimiters-nvim"},
  { import = "astrocommunity.editing-support.nvim-treesitter-endwise"},
  { import = "astrocommunity.editing-support.nvim-regexplainer"},
  { import = "astrocommunity.editing-support.neogen"},
  { import = "astrocommunity.editing-support.hypersonic-nvim"},
  { import = "astrocommunity.completion.cmp-cmdline"},
  { import = "astrocommunity.code-runner.compiler-nvim"},
  { import = "astrocommunity.code-runner.executor-nvim"},
  { import = "astrocommunity.code-runner.overseer-nvim"},
}

